/*
 * OpenUnison Helm Objects
 *
 * OpenUnison Helm Objects
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package helmmodel

type TrustedCertsInner struct {
	Name string `json:"name,omitempty"`
	PemB64 string `json:"pem_b64,omitempty"`
}
