/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecDeploymentDataResourcesRequests struct {
	Memory string `json:"memory,omitempty"`
	Cpu string `json:"cpu,omitempty"`
}
