/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreKeyPairsKeys struct {
	Name string `json:"name,omitempty"`
	TlsSecretName string `json:"tls_secret_name,omitempty"`
	ImportIntoKs string `json:"import_into_ks,omitempty"`
	ReplaceIfExists bool `json:"replace_if_exists,omitempty"`
	CreateData *OpenUnisonSpecKeyStoreKeyPairsCreateData `json:"create_data,omitempty"`
}
