/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreKeyPairsCreateDataSecretInfo struct {
	TypeOfSecret string `json:"type_of_secret,omitempty"`
	CertName string `json:"cert_name,omitempty"`
	KeyName string `json:"key_name,omitempty"`
}
