/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreKeyPairsCreateDataPatchInfo struct {
	Url string `json:"url,omitempty"`
	AnnotationName string `json:"annotation_name,omitempty"`
}
