/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecOpenshift struct {
	Git *OpenUnisonSpecOpenshiftGit `json:"git,omitempty"`
	BuilderImage string `json:"builder_image,omitempty"`
}
