/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecOpenunisonNetworkConfigurationErrorPages struct {
	Code int32 `json:"code,omitempty"`
	Location string `json:"location,omitempty"`
}
