/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStore struct {
	UpdateController *OpenUnisonSpecKeyStoreUpdateController `json:"update_controller,omitempty"`
	StaticKeys []OpenUnisonSpecKeyStoreStaticKeys `json:"static_keys,omitempty"`
	TrustedCertificates []OpenUnisonSpecKeyStoreTrustedCertificates `json:"trusted_certificates,omitempty"`
	KeyPairs *OpenUnisonSpecKeyStoreKeyPairs `json:"key_pairs,omitempty"`
}
