/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type Model struct{}
type ModelMap map[string]Model

type OpenUnisonStatus struct {
	Conditions                 *OpenUnisonStatusConditions `json:"conditions,omitempty"`
	Digest                     string                      `json:"digest,omitempty"`
	IdpCertificateFingerprints ModelMap                    `json:"idpCertificateFingerprints,omitempty"`
}
