/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreUpdateController struct {
	Image string `json:"image,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	DaysToExpire int32 `json:"days_to_expire,omitempty"`
}
