/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecDeploymentDataResources struct {
	Requests *OpenUnisonSpecDeploymentDataResourcesRequests `json:"requests,omitempty"`
	Limits *OpenUnisonSpecDeploymentDataResourcesRequests `json:"limits,omitempty"`
}
