/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreKeyPairs struct {
	CreateKeypairTemplate []OpenUnisonSpecAnnotations `json:"create_keypair_template,omitempty"`
	Keys []OpenUnisonSpecKeyStoreKeyPairsKeys `json:"keys,omitempty"`
}
