/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnison struct {
	Spec *OpenUnisonSpec `json:"spec,omitempty"`
	Status *OpenUnisonStatus `json:"status,omitempty"`
}
