/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreTrustedCertificates struct {
	Name string `json:"name,omitempty"`
	PemData string `json:"pem_data,omitempty"`
}
