/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecKeyStoreKeyPairsCreateData struct {
	TargetNamespace string `json:"target_namespace,omitempty"`
	SignByK8sCa bool `json:"sign_by_k8s_ca,omitempty"`
	ServerName string `json:"server_name,omitempty"`
	SubjectAlternativeNames []string `json:"subject_alternative_names,omitempty"`
	KeySize int32 `json:"key_size,omitempty"`
	CaCert bool `json:"ca_cert,omitempty"`
	DeletePodsLabels []string `json:"delete_pods_labels,omitempty"`
	PatchInfo *OpenUnisonSpecKeyStoreKeyPairsCreateDataPatchInfo `json:"patch_info,omitempty"`
	SecretInfo *OpenUnisonSpecKeyStoreKeyPairsCreateDataSecretInfo `json:"secret_info,omitempty"`
}
