/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecSamlRemoteIdp struct {
	Source *OpenUnisonSpecSource `json:"source,omitempty"`
	Mapping *OpenUnisonSpecMapping `json:"mapping,omitempty"`
}
