/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecOpenshiftGit struct {
	Repo string `json:"repo,omitempty"`
	Branch string `json:"branch,omitempty"`
	Dir string `json:"dir,omitempty"`
}
