/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecHosts struct {
	Names []OpenUnisonSpecNames `json:"names,omitempty"`
	IngressName string `json:"ingress_name,omitempty"`
	IngressType string `json:"ingress_type,omitempty"`
	SecretName string `json:"secret_name,omitempty"`
	Annotations []OpenUnisonSpecAnnotations `json:"annotations,omitempty"`
}
