/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecOpenunisonNetworkConfigurationQueueConfiguration struct {
	UseInternalQueue bool `json:"use_internal_queue,omitempty"`
	MaxProducers int32 `json:"max_producers,omitempty"`
	ConnectionFactory string `json:"connection_factory,omitempty"`
	MaxConsumers int32 `json:"max_consumers,omitempty"`
	MaxSessionsPerConnection int32 `json:"max_sessions_per_connection,omitempty"`
	TaskQueueName string `json:"task_queue_name,omitempty"`
	SmtpQueueName string `json:"smtp_queue_name,omitempty"`
	EncryptionKeyName string `json:"encryption_key_name,omitempty"`
	NumQueues int32 `json:"num_queues,omitempty"`
	MultiTaskQueues bool `json:"multi_task_queues,omitempty"`
	KeepAliveMillis int32 `json:"keep_alive_millis,omitempty"`
	Params []OpenUnisonSpecOpenunisonNetworkConfigurationQueueConfigurationParams `json:"params,omitempty"`
}
