/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonSpecNames struct {
	Name string `json:"name,omitempty"`
	ServiceName string `json:"service_name,omitempty"`
	EnvVar string `json:"env_var,omitempty"`
}
