/*
 * OpenUnison CRD
 *
 * OpenUnison ScaleJS Register API
 *
 * API version: v6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openunisonmodel

type OpenUnisonStatusConditions struct {
	LastTransitionTime string `json:"lastTransitionTime,omitempty"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type,omitempty"`
}
